name: Android CI

on:
  pull_request:
  push:
    branches:
    - 'main'
    - '7.**'

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:

    runs-on: ubuntu-latest-8-cores

    steps:
    - uses: actions/checkout@v4
      with:
          submodules: true

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        cache: gradle

    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v3

    - name: Build with Gradle
      run: ./gradlew qa

    - name: Archive reports for failed build
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: reports
        path: '*/build/reports'
